### ISSUE TITLE
results seem to be limited to 10 - pagination?

### ISSUE THREAD

**Issue by justinrush** [webtor-io/go-jackett#1]
I believe that there is some pagination happening as I can't get more than 10 results. Is there some way to page through or specify a larger result max size?

**Comment by vintikzzz** [comment]
There is no pagination involved, in my tests it returns hundreds of results. I think it can be the specific behaviour of indexers that you have selected.

**Comment by justinrush** [comment]
apparently what i was searching for just had the bland TV category that i was missing - thanks!
